### ISSUE TITLE
Handle OpenJDK 8's elimination of 'MaxPermSize' argument

### ISSUE THREAD

**Issue by allanlewis** [phracek/pycharm-community-edition#8] opened 2015-08-14 13:06 UTC
When I run `pycharm` from the command-line I get a warning from OpenJDK:

```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
```

Apparently this was removed in Java 8: http://stackoverflow.com/q/18339707/250673

Presumably we should be able to just remove this from the launch script?

**Comment by Christmas-Carol** [comment] 2016-07-06 01:41
How did you solve this problem?

**Comment by phracek** [comment] 2016-07-11 07:17
It can be caused by existing files ~/.PyCharm2016.1/pycharm{64}.vmoptions

Can you please look on it?

Line 137 from pycharm.sh file

**Comment by phracek** [comment] 2016-07-11 07:19
I have started pycharm from command line and output is:

~~~
$ pycharm 
[   1502]  ERROR -    #com.intellij.lang.Language - Language with ID 'Markdown' is already registered: class net.nicoulaj.idea.markdown.MarkdownLanguage 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.lang.Language.<init>(Language.java:87)
	at com.intellij.lang.Language.<init>(Language.java:72)
	at org.intellij.plugins.markdown.lang.MarkdownLanguage.<init>(MarkdownLanguage.java:25)
	at org.intellij.plugins.markdown.lang.MarkdownLanguage.<clinit>(MarkdownLanguage.java:22)
	at org.intellij.plugins.markdown.lang.MarkdownFileType.<init>(MarkdownFileType.java:30)
	at org.intellij.plugins.markdown.lang.MarkdownFileType.<clinit>(MarkdownFileType.java:27)
	at org.intellij.plugins.markdown.lang.MarkdownFileTypeFactory.createFileTypes(MarkdownFileTypeFactory.java:25)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:310)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:270)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:499)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:500)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:516)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:458)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:450)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[   1507]  ERROR -    #com.intellij.lang.Language - PyCharm Community Edition 2016.1.4  Build #PC-145.1504.1 
[   1507]  ERROR -    #com.intellij.lang.Language - JDK: 1.8.0_92 
[   1507]  ERROR -    #com.intellij.lang.Language - VM: OpenJDK 64-Bit Server VM 
[   1507]  ERROR -    #com.intellij.lang.Language - Vendor: Oracle Corporation 
[   1507]  ERROR -    #com.intellij.lang.Language - OS: Linux 
[  11993]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  GitLabIntegration) or icon jar:file:/home/phracek/.PyCharm2016.1/config/plugins/gitlab-integration-plugin/lib/gitlab-integration-plugin.jar!/com/neon/intellij/plugins/gitlab/icons/gitlab.jpg 
~~~

**Comment by phracek** [comment] 2016-07-13 10:06
@Christmas-Carol What version do you use? I did not discover a problem.

**Comment by xvitaly** [comment] 2021-04-24 11:22
Closing as PyCharm supports only its own bundled OpenJDK.

**Closed by xvitaly** 2021-04-24 11:22 UTC
